<a href="https://colab.research.google.com/github/qwerty141516/2026-BDA-repository/blob/main/code/06w_dataframe_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 인자 freq='W-TUE' 등

- 키워드 인자 freq = 'W-TUE'
  - 시작일이 매주 화요일

- 키워드 인자 freq = 'W-FRI'
  - 시작일이 매주 금요일

- 인자 freq = 'M'로 다음 시퀀스를 1달 후로 지정(deprecated)
  - 시작일은 start에 짖어한 날을 포함해서 월의 마지막 일자가 시작
  - freq='ME'로 지정

- 인자 freq = 'MS'로 지정
  - 시작일은 start에 지정한 날을 포함해서 월의 마지막 시작일자가 됨

In [2]:
import pandas as pd

dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [3]:
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [4]:
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_1290/746379463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [5]:
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

# 날짜를 포함한 데이터프레임

- 변수 dates에는 연속된 날짜 6개가 저장
  - 자동으로 freq = 'D'

- 위 dates를 index로 지정
  - 열 명은 각각 A, B, C, D 로 지정한 df생성

In [6]:
import numpy as np

dates = pd.date_range("20250302", periods = 6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [7]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2025-03-02  0.595137  0.626737 -1.080113 -0.662745
2025-03-03 -0.948061 -0.605969  0.216303 -0.492963
2025-03-04  0.901661 -0.135364  0.749204  0.264160
2025-03-05  0.019417 -1.126887 -1.069389  1.157294
2025-03-06  0.356952 -0.507067  1.033723  0.507639
2025-03-07 -0.346941 -0.076590  0.374050 -1.048630


# 다양한 자료형으로 구성된 데이터프레임

- 데이터 프레임 df2
   - 열 명이 'A'에서 'F'
   - 행 명이 0에서 3

In [8]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260408"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test","train","test","train"]),
    "F": "foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-04-08  1.0  3   test  foo
1  1.0 2026-04-08  1.5  3  train  foo
2  1.0 2026-04-08  2.0  3   test  foo
3  1.0 2026-04-08  2.5  3  train  foo

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

# 데이터프레임 열 참조

- 열로 구성된 시리즈 반환
  - df['열명']
  - df.열명

- 열로 구성된 데이터프레임 반환
  - df[['열명']]
  - df[['열명1', '열명2', '열명3' ...]]

In [10]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],

                  index=['윤일형','강수희', '홍소희','유한빈', '신수빈'],
                  columns=['중간','기말','과제','출석'])

pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [11]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [12]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [13]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [14]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [15]:
pf[['기말','출석','중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [16]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

# 조건에 맞는 행 참조

- df[조건]

In [17]:
pf['중간'] > 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [18]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [19]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [20]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

# df.loc[]
> 레이블이나 부울 배열을 통해 행과 열 그룹에 참조

- 조건
  - df.loc[조건]

- 단일 레이블
  - df.loc[1], df.loc['a']

- 레이블 목록 또는 배열
  - df.loc[['a','b','c']]

- 레이블 슬라이스
  - df.loc['a':'c']

In [21]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [22]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [23]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [24]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [25]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [26]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

# loc[index[i]]로 행 참조

- pf.loc[pf.index[0]]으로 첫 번째의 행 결과를 시리즈로 반환
  - pf.index[0]는 첫 번째 행 이름을 반환

In [27]:
pf.loc[pf.index[0]] # 첫번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [28]:
pf.loc[[pf.index[0]]] # 첫번째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [29]:
pf.loc[pf.index[1:4]] # 슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [30]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

# 열 참조

- pf.loc[:, '열명']으로 '열명' 전체를 시리즈로 반환

In [31]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [32]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [33]:
pf.loc[:, ['기말','출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

# loc[:, columns[i]]로 열 참조

- df.loc[:, pf.columns[0]]으로 첫 번째 열 결과를 시리즈로 반환
  - df.columns[0]은 첫 번째 열 이름을 반환

In [34]:
pf.loc[:, pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [35]:
pf.loc[:, [pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [36]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [37]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [38]:
pf.loc[:, pf.columns[1:]][['기말','과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

# 행과 열 참조

- df.loc['행명','열명'] 으로 행과 열에 맞는 한 원소를 참조

In [39]:
pf.loc['윤일형', '출석']

np.int64(18)

In [40]:
pf.loc['윤일형':'유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [41]:
pf.loc['윤일형':'유한빈','기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [42]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [43]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [44]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

# df.iloc[정수] 참조

- 행 참조
  - df.iloc[정수] 로 정수 index의 행을 참조

In [45]:
pf.iloc[1]

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [46]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [47]:
pf.iloc[[1, 3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [48]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

# df.iloc[:, 정수] 참조

- 열 참조
  - df.iloc[:, 정수]로 정수 columns의 열을 참조

In [49]:
df.iloc[:, 2]

2025-03-02   -1.080113
2025-03-03    0.216303
2025-03-04    0.749204
2025-03-05   -1.069389
2025-03-06    1.033723
2025-03-07    0.374050
Freq: D, Name: C, dtype: float64

In [50]:
df.iloc[:, [2]]

                   C
2025-03-02 -1.080113
2025-03-03  0.216303
2025-03-04  0.749204
2025-03-05 -1.069389
2025-03-06  1.033723
2025-03-07  0.374050

In [51]:
df.iloc[:, 1:]

                   B         C         D
2025-03-02  0.626737 -1.080113 -0.662745
2025-03-03 -0.605969  0.216303 -0.492963
2025-03-04 -0.135364  0.749204  0.264160
2025-03-05 -1.126887 -1.069389  1.157294
2025-03-06 -0.507067  1.033723  0.507639
2025-03-07 -0.076590  0.374050 -1.048630

# df.iloc[행번호, 열번호] 참조

- 행과 열에 대당하는 원소나 시리즈, 데이터프레임 참조열 참조

  - df.iloc[행번호, 열번호]

In [52]:
df.iloc[1, 1]

np.float64(-0.6059691933656335)

In [53]:
df.iloc[1:3, 1:]

                   B         C         D
2025-03-03 -0.605969  0.216303 -0.492963
2025-03-04 -0.135364  0.749204  0.264160

In [54]:
df.iloc[:, 1:]

                   B         C         D
2025-03-02  0.626737 -1.080113 -0.662745
2025-03-03 -0.605969  0.216303 -0.492963
2025-03-04 -0.135364  0.749204  0.264160
2025-03-05 -1.126887 -1.069389  1.157294
2025-03-06 -0.507067  1.033723  0.507639
2025-03-07 -0.076590  0.374050 -1.048630

In [55]:
df.iloc[[1, 3, 4], 1:]

                   B         C         D
2025-03-03 -0.605969  0.216303 -0.492963
2025-03-05 -1.126887 -1.069389  1.157294
2025-03-06 -0.507067  1.033723  0.507639

In [56]:
df.iloc[[1, 3, 4,],[0, 1]]

                   A         B
2025-03-03 -0.948061 -0.605969
2025-03-05  0.019417 -1.126887
2025-03-06  0.356952 -0.507067

# at['행명', '열명'] 참조

- 레이블 기반으로 참조하는 방식으로 단 하나의 원소를 참조
- 하나의 값을 참조하므로 속도가 빠른 장점

In [57]:
pf.at['윤일형', '과제']

np.int64(8)

In [58]:
pf.at['유한빈', '기말']

np.int64(22)

In [59]:
pf.at[pf.index[1], '출석']

np.int64(20)

In [60]:
pf.at[pf.index[3], pf.columns[2]]

np.int64(9)

# iat[i, j] 참조

- 정수 첨자 기반의 참조 방식으로 단 하나의 원소를 참조

In [61]:
pf.iat[1, 2]

np.int64(10)

In [62]:
pf.iat[2, 3]

np.int64(19)

# 데이터 프레임 준비

- 파일 '2016년졸음운전.csv'를 읽어 데이터프레임을 준비
  - 파일의 첫 열을 데이터프레임의 인덱스로 사용하기 위해 옵션 index_col=0을 지정해 읽기

In [63]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.096361 -0.304190  0.037296 -0.045874
std    0.672078  0.592619  0.907577  0.828981
min   -0.948061 -1.126887 -1.080113 -1.048630
25%   -0.255351 -0.581244 -0.747966 -0.620299
50%    0.188185 -0.321216  0.295176 -0.114401
75%    0.535591 -0.091284  0.655415  0.446770
max    0.901661  0.626737  1.033723  1.157294

In [64]:
df.T

   2025-03-02  2025-03-03  2025-03-04  2025-03-05  2025-03-06  2025-03-07
A    0.595137   -0.948061    0.901661    0.019417    0.356952   -0.346941
B    0.626737   -0.605969   -0.135364   -1.126887   -0.507067   -0.076590
C   -1.080113    0.216303    0.749204   -1.069389    1.033723    0.374050
D   -0.662745   -0.492963    0.264160    1.157294    0.507639   -1.048630

In [68]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [69]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

# 데이터프레임 합 계산

- df.sum() df.sum(axis=0)
  - 모든 열의 합
  - 축 axis=0에 따라 이동(위에서 아래로 수직으로)하며 합

- df.sum(axis=1)
  - 축 axis=1에 따라 이동(왼쪽에서 오른쪽으로 수평으로)하며 합 구하기
  - 모든 행의 합

In [71]:
df.sum(0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [72]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [73]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

# 데이터프레임 합 계산
> df.cumsum(axis= 0 | 1)

- 함수 cumsum()
  - 누적 합을 구하는 함수
  - df.cumsum(axis=0)
    - 위에서 아래로 수직으로 누적 합을 구하기

  - df.cumsum(axis=1)
    - 왼쪽에서 오른쪽으로 수평으로 누적 합

In [74]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [75]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

# 데이터 프레임 평균 계산

- df.mean() df.mean(axis=0)
  - 모든 열의 평균을 구하기
  - 축 axis=0에 따라 이동(위에서 아래로 수직으로)하며 평균

- df.mean(axis=1)
  - 축 axis=1에 따라 이동(왼쪽에서 오른쪽으로 수평으로)하며 평균
  - 모든 행의 평균을 구하기

- df.mean(axis=None)
  - 전체평균

In [77]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [78]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [79]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [80]:
df.mean(axis=None)

np.float64(206.38888888888889)

# 데이터프레임 최대 최소 계산

- df.max(), df.max(axis=0) 모든 열 최댓값
  - 축은 axis=0에 따라 이동(위에서 아래로 수직으로)하며 최댓값

- df.max(axis=1)
  - 축 axis=1에 따라 이동(왼쪽에서 오른쪽으로 수평으로)하며 최댓값
  - 모든 행의 최댓값

- df.max(axis=None)
  - 전체에서 최댓값

- df.min(), df.min(axis=0) 모든 열의 최솟값
  - 축 axis=0에 따라 이동(위에서 아래로 수직으로)하며 최솟값
  - 모든 열의 최솟값

- df.min(axis=1)
  - 축 axis=1 에 따라 이동(왼쪽에서 오른쪽으로 수평으로) 하며 최솟값
  - 모든 행의 최솟값

- df.min(axis=None)
  - 전체에서 최솟값

In [81]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [82]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [83]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [84]:
df.max(axis=None)

522

In [85]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [86]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [87]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [88]:
df.min(axis=None)

4

# 데이터프레임 조회

- df[['사망(명)','부상(명)']].sum(axis=1)
  - 모든 행의 '사망(명)'과 '부상(명)'의 합

- df.iloc[:, 1:].sum(axis=1)
  - 모든 행의 '사망(명)'과 '부상(명)'의 합

In [89]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [90]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

# 새로운 열 추가

- 새로운 df2를 만든 후

- '사망(명)' + '부상(명)'의 합을 새로운 '재해자수' 열에 대입

- df.loc['총계'] = df2.sum(axis=0)
  - 새로운 행 '총계' 생성
  - 모든 열의 합을 추가
  - axis=0는 생략 가능

In [92]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [93]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [94]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

# 블리안 인덱싱

- 데이터프레임 원소의 비교논리 값은 다음으로 반환
  - 원소 값이 10 초과인 자료가 있는 부분은 True가 표시

- 위의 블리안 인덱싱 조건을 df2[조건] 내부에 기술
  - True인 원소만 표시
  - False인 원소는 NaN이 표시

- df2[ [True, False, ...., False] ]
  - True인 행만 표시
  - 인위적으로 True False를 13개 만들어 실행
    - True인 처음 6개의 행만 표시

In [95]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [96]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [97]:
df2[ [True]*6 + [False]*7 ]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

# 조건과 isin()

- '재해자수' 열의 비교 논리 값은 다음으로 반환
  - 13개의 논리 값

- '재해자수'가 400명을 초과한 행을 표시

- 열 이름 '사명(명)'이 7인 논리 값의 시리즈가 반환된

- 함수 Series.isin([value0, value1, value2, ...])
  - 시리즈의 각 요소가 전달된 값 시퀀스의 요소와 정확히 일치하는지 여부를 보여주는 논리 값 시리즈를 반화
  - df['사망(명)'] == 7
    - 열 이름 '사망(명)'이 7인 논리 값의 시리즈가 반환

In [98]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [99]:
df2[df2['재해자수'] > 400 ]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [100]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [101]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

# isin(), str.contains()

- '사망(명)'이 7명 또는 10명인 모든 행을 표시

- 사망(명)은 7 또는 10이거나 부상(명)은 350을 초과하는 행을 모두 출력

- 행 명이나 열 명의 값이 문자열
  - 문자열에 퐇마된 내용은 함수 contain('부분문자열')로 검색

In [102]:
df[(df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [103]:
df[ df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

# 논리 첨자로 값 대입

- df3의 원소 값이 10보다 큰 모든 수를
  - 음수로 수정

In [104]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [105]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

# 함수 df.query(조건)

- 조건을 만족하는 행을 표시

In [106]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [107]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [108]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

# 열 이름을 바로 기술 가능

- 열 E가 "python"인 행을 반환
  - 외부와 내부의 따옴표를 작은 따옴표와 큰 따옴표로 구분

- 열 E가 "pypthon"이 아닌 행을 반환
  - 외부와 내부의 따옴표를 구분

In [109]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [110]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [111]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [112]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

# 열명 중간에 빈 문자열이 있는 경우

- 반드시 열 명을 백쿼드(back quote, Tab키 위의 키) `D clmns`를 사용

- 만일 "D clmns"으로 사용
  - 열 A의 값 문자열로 "D clumns"를 찾으므로 오류는 발생하지 않으나 원하는 결과가 표시되지 않음

In [113]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [114]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [115]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [116]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [117]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [118]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

# df.query() 내부의 질의 문자열 내부에서 변수를 사용

- @변수명을 사용
- f문자열로 사용이 가능
  - f 문자열 내부에서 변수 num은 {num}으로 사용이 가능

- 열 유형이 문자열
  - 열명.str.contains('부분문자열')을 사용
    - '부분문자열'이 포함된 행의 데이터프레임을 반환
  
- 열의 내용이 문자열
  - 열명.str.startswith('시작문자열')을 사용
    - '끝나는문자열'로 종료되는 행의 데이터프레임을 반환

In [119]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [120]:
num = 3
df.query(f'B >  {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [121]:
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [122]:
s = 'E.str.startswith("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [123]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [135]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

# df.head(n)

- df.tail(n)

In [136]:
df.head()

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522

In [137]:
df.head(7)

         사고(건)  사망(명)  부상(명)
연월
2016년1월    192      5    387
2016년2월    174      6    328
2016년3월    217      7    435
2016년4월    216      7    419
2016년5월    239     13    522
2016년6월    200     12    362
2016년7월    227      9    460

In [138]:
df.tail()

          사고(건)  사망(명)  부상(명)
연월
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [139]:
df.tail(6)

          사고(건)  사망(명)  부상(명)
연월
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

# 행 제목(레이블)으로 정렬

- axis = 0
  - ascending = False
    - 내림차순

In [140]:
df.sort_index()

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [141]:
df.sort_index(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347

In [142]:
df.sort_index(ascending=False)

          사고(건)  사망(명)  부상(명)
연월
2016년9월     187     13    347
2016년8월     230      7    490
2016년7월     227      9    460
2016년6월     200     12    362
2016년5월     239     13    522
2016년4월     216      7    419
2016년3월     217      7    435
2016년2월     174      6    328
2016년1월     192      5    387
2016년12월    168      4    364
2016년11월    200      5    418
2016년10월    183     10    367

# 열 제목(레이블)으로 정렬

- axis = 1
   -ascending = False
    - 내림차순

In [143]:
df.sort_index(axis=1)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [144]:
df.sort_index(axis=1, ascending=False)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

# 특정한 열의 내용으로 정렬
> df.sort_values(by = '열명')

- 인자 by
  - 열 하나 또는 열 목록 가능

- 인자 ascending = False
  - 내림차순

In [146]:
df.sort_values(by='사망(명)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년8월     230      7    490
2016년4월     216      7    419
2016년3월     217      7    435
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년5월     239     13    522
2016년9월     187     13    347

# 데이터프레임 행 값으로 정렬
> df.sort_values(by = '행명', axis=1)

- 행의 값에 따라 열의 순서가 정해짐
  - 인자 ascending = False
    - 내림차순

In [147]:
df.sort_values(by = '2016년12월' , axis=1)

          사망(명)  사고(건)  부상(명)
연월
2016년1월       5    192    387
2016년2월       6    174    328
2016년3월       7    217    435
2016년4월       7    216    419
2016년5월      13    239    522
2016년6월      12    200    362
2016년7월       9    227    460
2016년8월       7    230    490
2016년9월      13    187    347
2016년10월     10    183    367
2016년11월      5    200    418
2016년12월      4    168    364

In [148]:
df.sort_values(by=['2016년12월'], axis=1, ascending=False)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

# 데이터프레임 생성과 열명 지정

In [149]:
import numpy as np
import pandas as pd

dates = pd.date_range("20260408", periods=6)
df = pd.DataFrame(np.arange(24).reshape(6, 4), index=dates)
df

             0   1   2   3
2026-04-08   0   1   2   3
2026-04-09   4   5   6   7
2026-04-10   8   9  10  11
2026-04-11  12  13  14  15
2026-04-12  16  17  18  19
2026-04-13  20  21  22  23

In [150]:
df.columns = list('ABCD')
df

             A   B   C   D
2026-04-08   0   1   2   3
2026-04-09   4   5   6   7
2026-04-10   8   9  10  11
2026-04-11  12  13  14  15
2026-04-12  16  17  18  19
2026-04-13  20  21  22  23

# 열 추가
> 먼저 새로운 열에 삽입할 시리즈를 하나 생성

- 열 'E' 에 시리즈 s1을 대입
   - s1에는 2023-01-07이 없으므로 결측값에는 NaN 값이 삽입

In [154]:
s1 = pd.Series([1, 2, 3, 4, 5], index=pd.date_range("20260408", periods=5))
s1

2026-04-08    1
2026-04-09    2
2026-04-10    3
2026-04-11    4
2026-04-12    5
Freq: D, dtype: int64

In [155]:
df["E"] = s1
df

             A   B   C   D    E
2026-04-08   0   1   2   3  1.0
2026-04-09   4   5   6   7  2.0
2026-04-10   8   9  10  11  3.0
2026-04-11  12  13  14  15  4.0
2026-04-12  16  17  18  19  5.0
2026-04-13  20  21  22  23  NaN

# df.loc['행', '열'] = value
> 행 열 위치의 원소 값 수정

In [156]:
df.loc['2026-04-08', 'A'] = 10
df

             A   B   C   D    E
2026-04-08  10   1   2   3  1.0
2026-04-09   4   5   6   7  2.0
2026-04-10   8   9  10  11  3.0
2026-04-11  12  13  14  15  4.0
2026-04-12  16  17  18  19  5.0
2026-04-13  20  21  22  23  NaN

In [157]:
df.loc[dates[1], 'B'] = 50
df

             A   B   C   D    E
2026-04-08  10   1   2   3  1.0
2026-04-09   4  50   6   7  2.0
2026-04-10   8   9  10  11  3.0
2026-04-11  12  13  14  15  4.0
2026-04-12  16  17  18  19  5.0
2026-04-13  20  21  22  23  NaN

In [158]:
df.at[dates[2], df.columns[2]] = 100
df

             A   B    C   D    E
2026-04-08  10   1    2   3  1.0
2026-04-09   4  50    6   7  2.0
2026-04-10   8   9  100  11  3.0
2026-04-11  12  13   14  15  4.0
2026-04-12  16  17   18  19  5.0
2026-04-13  20  21   22  23  NaN

In [160]:
df.at[df.index[-1], df.columns[-1]] = 230
df

             A   B    C   D      E
2026-04-08  10   1    2   3    1.0
2026-04-09   4  50    6   7    2.0
2026-04-10   8   9  100  11    3.0
2026-04-11  12  13   14  15    4.0
2026-04-12  16  17   18  19    5.0
2026-04-13  20  21   22  23  230.0

# df.iloc[m, n] = value
> df.iat[m, n] = value

- df.iloc[:, 4] = 600
  - 열 첨자 4인 모든 값을 600으로 수정

In [161]:
df.iloc[1, 2] = 60
df

             A   B    C   D      E
2026-04-08  10   1    2   3    1.0
2026-04-09   4  50   60   7    2.0
2026-04-10   8   9  100  11    3.0
2026-04-11  12  13   14  15    4.0
2026-04-12  16  17   18  19    5.0
2026-04-13  20  21   22  23  230.0

In [162]:
df.iat[3, 3] = 150
df

             A   B    C    D      E
2026-04-08  10   1    2    3    1.0
2026-04-09   4  50   60    7    2.0
2026-04-10   8   9  100   11    3.0
2026-04-11  12  13   14  150    4.0
2026-04-12  16  17   18   19    5.0
2026-04-13  20  21   22   23  230.0

In [163]:
df.iloc[:, 4] = [500] * len(df)
df

             A   B    C    D      E
2026-04-08  10   1    2    3  500.0
2026-04-09   4  50   60    7  500.0
2026-04-10   8   9  100   11  500.0
2026-04-11  12  13   14  150  500.0
2026-04-12  16  17   18   19  500.0
2026-04-13  20  21   22   23  500.0

In [165]:
df.iloc[:, 4] = 600
df

             A   B    C    D      E
2026-04-08  10   1    2    3  600.0
2026-04-09   4  50   60    7  600.0
2026-04-10   8   9  100   11  600.0
2026-04-11  12  13   14  150  600.0
2026-04-12  16  17   18   19  600.0
2026-04-13  20  21   22   23  600.0

# 데이터프레임과 DatetimeIndex 생성

In [168]:
import numpy as np
import pandas as pd

dates = pd.date_range("20260408", periods=7, freq='W-MON')
df = pd.DataFrame(np.arange(35).reshape(7, 5), index=dates, columns=list('ABCDE'))
df

             A   B   C   D   E
2026-04-13   0   1   2   3   4
2026-04-20   5   6   7   8   9
2026-04-27  10  11  12  13  14
2026-05-04  15  16  17  18  19
2026-05-11  20  21  22  23  24
2026-05-18  25  26  27  28  29
2026-05-25  30  31  32  33  34

In [170]:
subdates = pd.date_range("20260408", periods=5, freq='W-MON')
subdates

DatetimeIndex(['2026-04-13', '2026-04-20', '2026-04-27', '2026-05-04',
               '2026-05-11'],
              dtype='datetime64[ns]', freq='W-MON')

# 시리즈 생성과 열 추가
> 결측 값을 대입

In [171]:
s = pd.Series(np.linspace(10, 17, 5), index=subdates)
s

2026-04-13    10.00
2026-04-20    11.75
2026-04-27    13.50
2026-05-04    15.25
2026-05-11    17.00
Freq: W-MON, dtype: float64

In [173]:
df['F'] = s
df

             A   B   C   D   E      F
2026-04-13   0   1   2   3   4  10.00
2026-04-20   5   6   7   8   9  11.75
2026-04-27  10  11  12  13  14  13.50
2026-05-04  15  16  17  18  19  15.25
2026-05-11  20  21  22  23  24  17.00
2026-05-18  25  26  27  28  29    NaN
2026-05-25  30  31  32  33  34    NaN

In [174]:
df2 = df.copy()
df2.iloc[3, 4] = np.nan
df2.iloc[1, :] = np.nan
df2

               A     B     C     D     E      F
2026-04-13   0.0   1.0   2.0   3.0   4.0  10.00
2026-04-20   NaN   NaN   NaN   NaN   NaN    NaN
2026-04-27  10.0  11.0  12.0  13.0  14.0  13.50
2026-05-04  15.0  16.0  17.0  18.0   NaN  15.25
2026-05-11  20.0  21.0  22.0  23.0  24.0  17.00
2026-05-18  25.0  26.0  27.0  28.0  29.0    NaN
2026-05-25  30.0  31.0  32.0  33.0  34.0    NaN

# 함수 isna()
> 결측 값 검사 함수

- isnull()로도 가능

In [175]:
df2

               A     B     C     D     E      F
2026-04-13   0.0   1.0   2.0   3.0   4.0  10.00
2026-04-20   NaN   NaN   NaN   NaN   NaN    NaN
2026-04-27  10.0  11.0  12.0  13.0  14.0  13.50
2026-05-04  15.0  16.0  17.0  18.0   NaN  15.25
2026-05-11  20.0  21.0  22.0  23.0  24.0  17.00
2026-05-18  25.0  26.0  27.0  28.0  29.0    NaN
2026-05-25  30.0  31.0  32.0  33.0  34.0    NaN

In [176]:
pd.isna(df2)

                A      B      C      D      E      F
2026-04-13  False  False  False  False  False  False
2026-04-20   True   True   True   True   True   True
2026-04-27  False  False  False  False  False  False
2026-05-04  False  False  False  False   True  False
2026-05-11  False  False  False  False  False  False
2026-05-18  False  False  False  False  False   True
2026-05-25  False  False  False  False  False   True

In [177]:
df2.isna()

                A      B      C      D      E      F
2026-04-13  False  False  False  False  False  False
2026-04-20   True   True   True   True   True   True
2026-04-27  False  False  False  False  False  False
2026-05-04  False  False  False  False   True  False
2026-05-11  False  False  False  False  False  False
2026-05-18  False  False  False  False  False   True
2026-05-25  False  False  False  False  False   True

In [178]:
df2.isnull()

                A      B      C      D      E      F
2026-04-13  False  False  False  False  False  False
2026-04-20   True   True   True   True   True   True
2026-04-27  False  False  False  False  False  False
2026-05-04  False  False  False  False   True  False
2026-05-11  False  False  False  False  False  False
2026-05-18  False  False  False  False  False   True
2026-05-25  False  False  False  False  False   True

# df.count()
> 열 마다 결측 값이 없는 개수

- axis = 1
  - 행마다 결측 값이 없는 개수

In [179]:
df2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [180]:
df2.count(axis=1)

2026-04-13    6
2026-04-20    0
2026-04-27    6
2026-05-04    5
2026-05-11    6
2026-05-18    5
2026-05-25    5
Freq: W-MON, dtype: int64

# 함수 calue_counts()
> df2.열명.value_counts()

- df2.열명.value_counts()
- df2['열명'].value_counts()
  - 열에서 유일한 값들의 출현 빈도수를 표시, nan은 미포함
  - 유형 Seies, 유일 값이 첨자
  - 키워드 인자 dropna=False
    - nan도 포함해서 유일한 값들의 출현 빈도수를 표시

- to_frame()으로 호출
  - 데이터프레임 반환

In [181]:
s = df2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [182]:
type(s)

pandas.core.series.Series

In [183]:
s[4]

np.int64(1)

In [184]:
s.values

array([1, 1, 1, 1, 1])

In [185]:
df2['D'].value_counts()

D
3.0     1
13.0    1
18.0    1
23.0    1
28.0    1
33.0    1
Name: count, dtype: int64

In [186]:
df2['D'].value_counts().to_frame(0)

      0
D
3.0   1
13.0  1
18.0  1
23.0  1
28.0  1
33.0  1

In [187]:
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

# df2.value_counts()

- 데이터프레임에서 각 개별 행의 빈도를 포함하는 시리즈를 반환
  - 물론 결측값 nan은 제외
    - dropna = False로 포함
  - 모든 행의 값 구성이 다르므로 모든 행이 첨자이며, 값이 모두 1

In [188]:
df2.value_counts(dropna=False)

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   10.00    1
10.0  11.0  12.0  13.0  14.0  13.50    1
15.0  16.0  17.0  18.0  NaN   15.25    1
20.0  21.0  22.0  23.0  24.0  17.00    1
25.0  26.0  27.0  28.0  29.0  NaN      1
30.0  31.0  32.0  33.0  34.0  NaN      1
NaN   NaN   NaN   NaN   NaN   NaN      1
Name: count, dtype: int64

In [189]:
s1 = df2.value_counts()
s1

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   10.0    1
10.0  11.0  12.0  13.0  14.0  13.5    1
20.0  21.0  22.0  23.0  24.0  17.0    1
Name: count, dtype: int64

In [190]:
s1.index

MultiIndex([( 0.0,  1.0,  2.0,  3.0,  4.0, 10.0),
            (10.0, 11.0, 12.0, 13.0, 14.0, 13.5),
            (20.0, 21.0, 22.0, 23.0, 24.0, 17.0)],
           names=['A', 'B', 'C', 'D', 'E', 'F'])

In [191]:
s1.values

array([1, 1, 1])

# 함수 dropna()

- dropna() dropna(axis=0)
  - NaN인 결측값이 하나라도 있는 행을 제거한 데이터프레임을 반환
  - 기본적으로 제거된 것이 df2에 자동으로 반영되지 않음

- dropna(axis=1)
  - NaN인 결측값이 하나라도 있을 였을 제거한 데이터프레임을 반환
    - 다음에서 모든 열이 제거

In [192]:
df2.dropna()

               A     B     C     D     E     F
2026-04-13   0.0   1.0   2.0   3.0   4.0  10.0
2026-04-27  10.0  11.0  12.0  13.0  14.0  13.5
2026-05-11  20.0  21.0  22.0  23.0  24.0  17.0

In [194]:
df.dropna(axis=0)

             A   B   C   D   E      F
2026-04-13   0   1   2   3   4  10.00
2026-04-20   5   6   7   8   9  11.75
2026-04-27  10  11  12  13  14  13.50
2026-05-04  15  16  17  18  19  15.25
2026-05-11  20  21  22  23  24  17.00

In [195]:
df.dropna(axis=1)

             A   B   C   D   E
2026-04-13   0   1   2   3   4
2026-04-20   5   6   7   8   9
2026-04-27  10  11  12  13  14
2026-05-04  15  16  17  18  19
2026-05-11  20  21  22  23  24
2026-05-18  25  26  27  28  29
2026-05-25  30  31  32  33  34

# 결측값에 값을 대입

- df2[ df2.isna() ] = 500
  - 모든 결측값에 500을 대입

In [196]:
df2[ df2.isna() ] = 500
df2

                A      B      C      D      E       F
2026-04-13    0.0    1.0    2.0    3.0    4.0   10.00
2026-04-20  500.0  500.0  500.0  500.0  500.0  500.00
2026-04-27   10.0   11.0   12.0   13.0   14.0   13.50
2026-05-04   15.0   16.0   17.0   18.0  500.0   15.25
2026-05-11   20.0   21.0   22.0   23.0   24.0   17.00
2026-05-18   25.0   26.0   27.0   28.0   29.0  500.00
2026-05-25   30.0   31.0   32.0   33.0   34.0  500.00

# 결측값을 채우는 함수 fillna()

- 함수 호출 df.fillna(10)의 결과
  - df 결측값을 모두 10으로 채움
  - 함수 fillna()의 인자 inplace=False가 기본
    - df 자체에 수정이 반영되지는 않음
    - 여전히 df는 많은 결측값이 있는 이전과 동일

In [197]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [198]:
df.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [199]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

# fillna(value, limit=n, axis = 0 | 1)
> 열(axis= 0)이나 행(axis= 1)에서 결측 값에 value를 채우는 최대 수

- df.fillna('missing', axis=0), df.fillna('missing')
  - 모든 결측값에 문자열 'missing'을 채움
  - 키워드 인자 limit이 없으면 인자 axis = 0 | 1은 별 의미가 없음
  - 키워드 인자 limit=1
    - 각 열에서 최대 1개만 채움
    - C 열의 첫 행만 missing으로 채워짐

- 다음은 동일 기능
  - df.fillna('missing', limit=1)
  - df.fillna('missing', limit=1, axis=0)

In [200]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [201]:
df.fillna('missing', axis=0)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0  missing      1.0
2  missing  missing  missing  missing
3  missing      3.0  missing      4.0

In [202]:
df.fillna('missing', limit=1)

         A        B        C        D
0  missing      2.0  missing      0.0
1      3.0      4.0      NaN      1.0
2      NaN  missing      NaN  missing
3      NaN      3.0      NaN      4.0

In [203]:
df.fillna('missing',limit=1, axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

In [204]:
df.fillna('value', axis=1)

       A      B      C      D
0  value    2.0  value    0.0
1    3.0    4.0  value    1.0
2  value  value  value  value
3  value    3.0  value    4.0

# fillna(value)
> value에 스칼라, dict, Series 또는 DataFrame 대입 가능, 리스트는 대입 불가능

- values = {"A":100, "B":200, "C":300, "D":400}
  - 채워 넣는 값으로 dict를 사용한 예
  - 사전의 키는 열 명이며, 값은 결측값을 대체할 값
  - 인자 value=values로 호출
    - 각각 열 별로 채워진 값이 다름
  
- df.fillna(value=values, limit=2)
  - 키워드 인자 limit=2
    - 각 열 별로 채워지는 수를 2개로 제한

In [205]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [206]:
values = {"A":100, "B":200, "C":300, "D":400}
df.fillna(value=values)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0  300.0  400.0
3  100.0    3.0  300.0    4.0

In [207]:
df.fillna(value=values, limit=2)

       A      B      C      D
0  100.0    2.0  300.0    0.0
1    3.0    4.0  300.0    1.0
2  100.0  200.0    NaN  400.0
3    NaN    3.0    NaN    4.0

# fillna(value)
> 시리즈와 데이터프레임으로 대입

- df2에 열 D가 없으므로 열 D인 결측값은 대체되지 못함

In [208]:
s = pd.Series([100, 200, 400], index=list('ACD'))
s

A    100
C    200
D    400
dtype: int64

In [209]:
df.fillna(value=s, limit=1)

       A    B      C      D
0  100.0  2.0  200.0    0.0
1    3.0  4.0    NaN    1.0
2    NaN  NaN    NaN  400.0
3    NaN  3.0    NaN    4.0

In [210]:
df2 = pd.DataFrame(-np.ones((4, 4)), columns=list('ABCE'))
df2

     A    B    C    E
0 -1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0

# 결측값을 위한 함수 fillna(method='ffill')
> 향후 obj.ffill()와 obj.bfill() 메소드로 대체될 함수

- df.fillna(method='ffill')
  - 결측값을 달리 지정하지 않고
  - 바로 열의 바로 이전에 있는 내용으로 채움
    - 마지막 유효한 값을 다음 유효한 값으로 전파하여 채우는 방식
  
  - 행 0, 열 A인 원소는 이전 값이 없으므로 채워지지 못함
    - 열 C 도 마찬가지

- df.fillna(method='ffill',limit=1)
  - 키워드 인자 limit=1로 이전 값으로 최대 하나만 채움

- df.fillna(method='bfill',limit=1)
  - method='bfill'
    - 데이터프레임에서 바로 열의 이후에 있는 내용으로 채우려면
    - 즉, 결측값을 채우기 위해 다음 유효한 관찰 값을 사용하여 결측값을 채움
    - 키워드 인자 limit=1로 이후 값으로 최대 하나만 채움

In [211]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [213]:
df.fillna(method='ffill')

# A, B, D의 수가 아래의 NaN을 다 채움

/tmp/ipykernel_1290/3506802679.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [216]:
df.fillna(method='ffill' ,limit=1)

# A, B, D의 수가 아래의 NaN을 하나만 채움

/tmp/ipykernel_1290/1140427366.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill' ,limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  NaN  3.0 NaN  4.0

In [217]:
df.fillna(method='bfill' ,limit=1)

# A, B, D의 맨 아래의 수(NaN이 아닌)가 위의 행을 하나만 채움

/tmp/ipykernel_1290/832458199.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill' ,limit=1)

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  3.0 NaN  4.0
3  NaN  3.0 NaN  4.0

# df.fillna(df.mean())

- 대체할 값으로 각 열의 평균값을 넣는 방법
  - C 열은 모두 결측값으로 대체하지 못함

In [218]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [219]:
df.mean()

A    3.000000
B    3.000000
C         NaN
D    1.666667
dtype: float64

In [220]:
df.fillna(df.mean())

     A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

# df.fillna(df.mean()['A':'B'])

- df.fillna(df.mean()['A':'B'])
  - 대체할 값으로 각각 열 A와 B의 평균값을 넣는 방법
  - C 열은 모두 결측값으로 대체하지 못하며
  - 열 D는 지정하지 않았으므로 대체하지 못함

df.fillna(df.mean()['D'])
  - 모든 결측값을 열 D의 평균값으로 채움

In [221]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [222]:
df.fillna(df.mean()['A':'B'])

     A    B   C    D
0  3.0  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  3.0 NaN  NaN
3  3.0  3.0 NaN  4.0

In [223]:
df.fillna(df.mean()['D'])

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000  1.666667  1.000000
2  1.666667  1.666667  1.666667  1.666667
3  1.666667  3.000000  1.666667  4.000000

# df.fillna(df.mean()['D'],limit=1)

- df.fillna(df.mean()['D'], limit=1)
  df.fillna(df.mean()['D'], limit=1, axis=0)
    - 인자 limit=1로 각 열에서 1개만 채움
  
- df.fillna(df.mean()['D'], limit=1, axis=1)
  - 인자 axis=1로 각 행에서 최대 1개만 채움

In [224]:
df

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [225]:
df.fillna(df.mean()['D'], limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [227]:
df.fillna(df.mean()['D'], limit=1, axis=0)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000

In [228]:
df.fillna(df.mean()['D'], limit=1, axis=1)

          A    B         C    D
0  1.666667  2.0       NaN  0.0
1  3.000000  4.0  1.666667  1.0
2  1.666667  NaN       NaN  NaN
3  1.666667  3.0       NaN  4.0